source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

xcodeproj 'LGBLog.xcodeproj'

target 'LGBLog_Example' do
  pod 'LGBLog', :path => '../'
end

target 'LGBLog_Tests' do
  pod 'LGBLog', :path => '../'

  
end
